INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES
('Molinillo de Café Manual', 'Molinillo de café compacto para café en grano recién molido.', '22.99', '1'),
('Diario de cuero hecho a mano', 'Hermoso diario encuadernado en cuero para escribir y dibujar.', '39.99', '102'),
('Hiking Water Bottle with Filter', 'Botella de agua de 8oz con filtro incorporado para beber agua limpia.', '29.99', '105'),
('Sweetened Condensed Milk', 'Leche rica y cremosa perfecta para hornear o postres.', '1.89', '108'),
('Maxi Wrap Dress', 'Un maxi vestido fluido perfecto tanto para ocasiones informales como semiformales.', '49.99', '109'),
('Tocino Ahumado Applewood', 'Delicioso tocino con un rico sabor ahumado applewood.', '6.99', '109'),
('Chupitos de Jengibre y Cúrcuma', 'Chupitos listos para beber hechos con jengibre fresco y cúrcuma.', '3.99', '11'),
('Alitas de Pollo Teriyaki', 'Sabrosas alitas de pollo marinadas en un dulce glaseado teriyaki.', '10.99', '11'),
('Esterilla de yoga', 'Esterilla de yoga antideslizante para un agarre y comodidad óptimos.', '25', '114'),
('Chubasquero ligero', 'Chubasquero impermeable ideal para actividades al aire libre, con un diseño plegable.', '79.99', '12'),
('Mini purificador de aire', 'Purificador de aire a pilas para espacios pequeños.', '49.99', '121'),
('Infrared Thermometer Gun', 'Termómetro sin contacto para lecturas de temperatura rápidas y fáciles.', '29.99', '121'),
('Cubierta de playa', 'Cubierta ligera perfecta para la playa, con un diseño ventoso.', '29.99', '122'),
('Pineapple Teriyaki Chicken Mix', 'Una mezcla perfecta de piña y teriyaki para saltear.', '6.99', '127'),
('Puré cremoso de patatas al ajo', 'Rico y mantecoso puré de patatas con ajo asado.', '3.99', '127'),
('Sweet Chili Dipping Sauce', 'Una salsa dulce y picante ideal para rollitos de primavera o nuggets de pollo.', '2.99', '127'),
('Trozos de piña (en lata)', 'Dulces trozos de piña en almíbar.', '2.29', '128'),
('Herbal Tea Set', 'Surtido de bolsitas de té de hierbas para la relajación y el bienestar.', '19.99', '132'),
('Hojaldre', 'Hojaldre versátil para tartas y pasteles.', '5.49', '137'),
('Auriculares con supresión de ruido', 'Auriculares de alta calidad que bloquean el ruido externo para una escucha envolvente.', '119.99', '138'),
('Guantes de jardinería con garras', 'Guantes duraderos con garras incorporadas para cavar y plantar.', '24.99', '141'),
('Kit de rollos de canela', 'Todo lo que necesita para hacer en casa rollos de canela que se derriten en la boca.', '6.89', '142'),
('Mezcla de ensalada de col', 'Mezcla de ensalada de col fresca y zanahoria para ensaladas.', '2.29', '148'),
('Mermelada de moras', 'Deliciosa mermelada casera de moras.', '4.29', '155'),
('Nutty Granola Clusters', 'Crujientes racimos de granola mezclados con frutos secos y miel.', '2.49', '164'),
('Aceite de Oliva', 'Aceite de oliva virgen extra, ideal para cocinar y ensaladas.', '7.99', '165'),
('Salsa de Miel y Mostaza', 'Cremosa salsa de miel y mostaza para mojar o aliñar.', '3.29', '166'),
('Tacos Veganos', 'Tacos veganos congelados rellenos de proteína vegetal y especias.', '7.49', '169'),
('Luxury Bathrobe', 'Suave y acogedor albornoz perfecto para relajarse en casa.', '49.99', '172'),
('Sudadera con capucha gráfica', 'Sudadera con capucha de atrevidos gráficos, cómoda y suave tejido', '49.99', '176'),
('Bloques de yoga ecológicos', 'Bloques de espuma sostenibles para la práctica del yoga.', '15.99', '176'),
('Frutas bañadas en chocolate', 'Frutas bañadas en rico chocolate, perfectas para postres.', '5.99', '184'),
('Manoplas de horno con bolsillo', 'Manoplas de horno de silicona diseñadas para cocinar y hornear con seguridad.', '19.99', '185'),
('Ventilador Eléctrico Portátil', 'Ventilador compacto para refrigeración personal en el trabajo o en casa.', '24.99', '186'),
('Barbecue Chicken Pizza', 'Pizza con pollo a la barbacoa, queso y cebolla roja.', '8.99', '19'),
('Mezcla de sopa de miso', 'Mezcla instantánea de sopa de miso, sólo añadir agua caliente para una comida caliente.', '3.29', '190'),
('Salsa barbacoa picante', 'Una salsa barbacoa ácida y picante perfecta para asar.', '3.99', '190'),
('Esterilla de Yoga', 'Esterilla de yoga antideslizante para un agarre y comodidad óptimos.', '25', '198'),
('Samosas Vegetales', 'Crujiente hojaldre relleno de verduras sazonadas.', '4.99', '201'),
('Luz nocturna luminosa', 'Luz nocturna de suave resplandor para habitaciones infantiles o junto a la cama.', '15.99', '204'),
('Wooden Kitchen Utensil Set', 'Juego de utensilios ecológicos hechos de madera natural.', '19.99', '21'),
('Tacos Veganos', 'Tacos veganos congelados rellenos de proteína vegetal y especias.', '7.49', '210'),
('Paint By Numbers Kit', 'Relajante kit de pintura con lienzo preimpreso para pintar.', '24.99', '210'),
('Salsa Marinara', 'Salsa marinara clásica para todos los platos de pasta.', '3.49', '216'),
('Barritas de granola con miel y almendras', 'Barritas de granola con miel y almendras', '3.99', '216'),
('Snack Container Set', 'Recipientes apilables para organizar aperitivos y golosinas.', '19.99', '218'),
('Kid''s Fruit Snacks', 'Surtido de snacks de gominola con sabor a fruta que encantan a los niños.', '2.49', '218'),
('Azúcar Granulado', 'Azúcar granulado fino para todas sus necesidades de repostería.', '2.49', '219'),
('Semillas de calabaza', 'Crujientes semillas de calabaza tostadas, ideales para picar', '2.79', '22'),
('Palitos de ajo', 'Palitos de ajo listos para hornear, perfectos para acompañar platos de pasta.', '3.49', '221'),
('Electric Nail File Kit', 'Set profesional para manicura y pedicura.', '34.99', '227'),
('Eco-Friendly Yoga Blocks', 'Bloques de espuma sostenibles para la práctica del yoga.', '15.99', '228'),
('Salsa picante', 'Salsa picante hecha con ingredientes frescos.', '2.29', '231'),
('Tabla de cortar de bambú', 'Tabla de cortar de bambú ecológica para preparar la comida.', '22', '238'),
('Almendras ecológicas', 'Almendras crujientes y nutritivas, perfectas para picar', '8.99', '239'),
('Mermelada de albaricoque', 'Dulce y sabrosa mermelada hecha de albaricoques naturales.', '4.29', '239'),
('Mochila', 'Mochila duradera y espaciosa para viajes y escuela.', '49.99', '239'),
('Spicy Beef Taco Mix', 'Mezcla fácil para hacer tacos de carne picante.', '1.99', '239'),
('Blue Corn Tortilla Chips', 'Crujientes chips hechos de maíz azul, perfectos para mojar.', '3.49', '246'),
('Fiambrera aislante', 'Fiambrera duradera diseñada para mantener la comida fresca y fría.', '24.99', '25'),
('Manta de felpa suave', 'Acogedora manta perfecta para las noches frías.', '29.99', '250'),
('Riñonera de moda', 'Moderna riñonera para llevar las manos libres', '34.99', '251'),
('Foam Building Blocks for Kids', 'Bloques de espuma blanda perfectos para la construcción y el juego imaginativo.', '22.99', '262'),
('Botiquín de primeros auxilios', 'Completo botiquín para situaciones de emergencia.', '29.99', '263'),
('Infusor de té de hierbas', 'Infusor para preparar fácilmente infusiones de hojas sueltas.', '9.99', '268'),
('Classic Cheeseburger Mix', 'Mezcla todo en uno para hamburguesas caseras fáciles, sólo añadir carne picada.', '5.49', '272'),
('Garlic Parmesan Wings', 'Alitas de pollo congeladas con salsa de ajo y parmesano.', '8.99', '275'),
('Albornoz de Lujo', 'Albornoz suave y afelpado para estar cómodo después de la ducha.', '49.99', '276'),
('Arroz de coliflor salteado', 'Arroz de coliflor congelado mezclado con verduras mixtas y condimentos.', '4.99', '279'),
('Phone Screen Protector', 'Protector de pantalla de cristal templado para smartphones.', '12.99', '280'),
('Digital Drawing Tablet', 'Tableta para dibujo digital y trabajos de ilustración.', '79.99', '283'),
('Korma de verduras', 'Cremoso curry de verduras enriquecido con especias.', '6.49', '288'),
('Stainless Steel BBQ Grill Set', 'Herramientas esenciales para barbacoas al aire libre incluyendo pinzas y espátula.', '49.99', '290'),
('Stick Vacuums Cleaner', 'Aspiradora sin cable para limpiezas rápidas.', '129.99', '292'),
('Compost Bin', 'Contenedor de compost para residuos de cocina.', '29.99', '294'),
('Classic Slim Fit Shirt', 'Una camisa entallada a medida para un look elegante en el trabajo.', '49.99', '294'),
('Cacao Nibs', 'Crujientes nibs de cacao, ideales para añadir a batidos o para hornear.', '6.49', '295'),
('Pumpkin Spice Granola', 'Crujiente granola con sabor a especias de calabaza.', '4.99', '30'),
('Colchón de aire', 'Colchón de aire inflable para dormir cómodamente.', '49.99', '33'),
('Tazas de mantequilla de almendras', 'Ricas tazas de chocolate rellenas de mantequilla de almendras, una deliciosa golosina.', '3.29', '35'),
('Maple Almond Granola', 'Crujiente granola con sabor a arce y trocitos de almendra para el desayuno.', '5.49', '41'),
('Graphic Print Leggings', 'Leggings de moda con un estampado gráfico único, versátiles para entrenamientos y ropa casual.', '29.99', '42'),
('Vegetable Quinoa Bowl', 'Comida congelada con quinoa y verduras mixtas, lista para calentar y comer.', '5.99', '54'),
('Sudadera gráfica', 'Una cómoda sudadera con un atrevido estampado gráfico.', '34.99', '55'),
('Jarra de agua de acero inoxidable', 'Jarra con aislamiento para mantener las bebidas frías o calientes.', '39.99', '56'),
('Blue Corn Tortilla Chips', 'Crujientes chips hechos de maíz azul, perfectos para mojar.', '3.49', '58'),
('Abridor eléctrico de tarros y botellas', 'Abre fácilmente tapas de tarros y botellas con un solo toque.', '24.99', '68'),
('Collar de adiestramiento para perros', 'Collar de adiestramiento recargable para un adiestramiento eficaz del comportamiento.', '39.99', '69'),
('Chili de ternera', 'Chili de ternera sustancioso, listo para calentar y comer.', '4.5', '69'),
('Tarta de chocolate y frambuesa', 'Rica tarta rellena de chocolate y frambuesa, un postre gourmet.', '9.99', '70'),
('Tortitas de suero de mantequilla', 'Esponjosas tortitas con sabor a suero de mantequilla.', '3.99', '73'),
('Calentador de manos recargable', 'Calentador portátil recargable para días fríos.', '22.99', '76'),
('Pet Hair Remover', 'Rodillo eficaz para quitar el pelo de mascota de los muebles.', '9.99', '79'),
('Infusor de té', 'Infusor de té de silicona para preparar té de hojas sueltas.', '12.99', '8'),
('Bolsas biodegradables para excrementos de perro', 'Bolsas ecológicas para recoger los excrementos de su mascota.', '14.99', '8'),
('Accesorio para aspiradora de pelo de mascota', 'Accesorio especial para aspiradoras para eliminar fácilmente el pelo de mascota.', '14.99', '80'),
('Sopa Cremosa de Tomate y Albahaca', 'Rica y cremosa sopa de tomate y albahaca, perfecta con un queso a la plancha.', '3.29', '83'),
('Botas de piel de caña alta', 'Duraderas botas de piel de caña alta para el aventurero con estilo.', '99.99', '84'),
('Smart Plug', 'Enchufe con Wi-Fi para controlar dispositivos desde tu smartphone.', '19.99', '89'),
('Pumpkin Pie Spice', 'Una mezcla de especias que aporta el sabor del otoño a tus productos horneados.', '2.99', '92');