INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES
('Manual Coffee Grinder', 'Compact coffee grinder for fresh ground coffee beans.', '22.99', '1'),
('Handmade Leather Journal', 'Beautiful leather-bound journal for writing and sketching.', '39.99', '102'),
('Hiking Water Bottle with Filter', '8oz water bottle with built-in filter for clean drinking water.', '29.99', '105'),
('Sweetened Condensed Milk', 'Rich and creamy milk perfect for baking or desserts.', '1.89', '108'),
('Maxi Wrap Dress', 'A flowy maxi dress perfect for both casual and semi-formal occasions.', '49.99', '109'),
('Applewood Smoked Bacon', 'Delicious bacon with a rich applewood smoked flavor.', '6.99', '109'),
('Ginger Turmeric Shots', 'Ready-to-drink shots made with fresh ginger and turmeric.', '3.99', '11'),
('Teriyaki Chicken Wings', 'Flavorful chicken wings marinated in a sweet teriyaki glaze.', '10.99', '11'),
('Yoga Mat', 'Non-slip yoga mat for optimal grip and comfort.', '25', '114'),
('Lightweight Rain Jacket', 'Water-resistant jacket ideal for outdoor activities, featuring a packable design.', '79.99', '12'),
('Mini Air Purifier', 'Battery-operated air purifier for small spaces.', '49.99', '121'),
('Infrared Thermometer Gun', 'Non-contact thermometer for quick and easy temperature readings.', '29.99', '121'),
('Beach Cover-Up', 'Lightweight cover-up perfect for the beach, with a breezy design.', '29.99', '122'),
('Pineapple Teriyaki Chicken Mix', 'A perfect blend of pineapple and teriyaki for stir-fry.', '6.99', '127'),
('Creamy Garlic Mashed Potatoes', 'Rich and buttery mashed potatoes with roasted garlic.', '3.99', '127'),
('Sweet Chili Dipping Sauce', 'A sweet and spicy sauce ideal for spring rolls or chicken nuggets.', '2.99', '127'),
('Pineapple Chunks (canned)', 'Sweet pineapple chunks in syrup.', '2.29', '128'),
('Herbal Tea Set', 'Assorted herbal tea bags for relaxation and wellness.', '19.99', '132'),
('Puff Pastry', 'Versatile puff pastry for pies and pastries.', '5.49', '137'),
('Noise-Canceling Headphones', 'High-quality headphones that block out external noise for immersive listening.', '119.99', '138'),
('Gardening Gloves with Claws', 'Durable gloves with built-in claws for digging and planting.', '24.99', '141'),
('Cinnamon Roll Kit', 'Everything you need to make melt-in-your-mouth cinnamon rolls at home.', '6.89', '142'),
('Cabbage Slaw Mix', 'Fresh cabbage and carrot slaw mix for salads.', '2.29', '148'),
('Blackberry Jam', 'Delicious homemade style blackberry jam.', '4.29', '155'),
('Nutty Granola Clusters', 'Crunchy granola clusters mixed with nuts and honey.', '2.49', '164'),
('Olive Oil', 'Extra virgin olive oil, ideal for cooking and salads.', '7.99', '165'),
('Honey Mustard Sauce', 'Creamy honey mustard sauce for dipping or dressing.', '3.29', '166'),
('Vegan Tacos', 'Frozen vegan tacos filled with plant-based protein and spices.', '7.49', '169'),
('Luxury Bathrobe', 'Soft and cozy bathrobe perfect for relaxing at home.', '49.99', '172'),
('Graphic Hoodie', 'Bold graphic hoodie featuring a comfortable fit and soft fabric.', '49.99', '176'),
('Eco-Friendly Yoga Blocks', 'Sustainable foam blocks for yoga practice.', '15.99', '176'),
('Chocolate Dipped Fruit', 'Fruits dipped in rich chocolate, perfect for desserts.', '5.99', '184'),
('Oven Mitts with Pocket', 'Silicone oven mitts designed for safe cooking and baking.', '19.99', '185'),
('Portable Electric Fan', 'Compact fan for personal cooling at work or home.', '24.99', '186'),
('Barbecue Chicken Pizza', 'Pizza topped with barbecue chicken, cheese, and red onions.', '8.99', '19'),
('Miso Soup Mix', 'Instant miso soup mix, just add hot water for a warm meal.', '3.29', '190'),
('Spicy BBQ Sauce', 'A tangy and spicy BBQ sauce that''s perfect for grilling.', '3.99', '190'),
('Yoga Mat', 'Non-slip yoga mat for optimal grip and comfort.', '25', '198'),
('Vegetable Samosas', 'Crispy pastry filled with seasoned vegetables.', '4.99', '201'),
('Luminous Night Light', 'Soft glow night light for children''s rooms or bedside.', '15.99', '204'),
('Wooden Kitchen Utensil Set', 'Eco-friendly utensil set made from natural wood.', '19.99', '21'),
('Vegan Tacos', 'Frozen vegan tacos filled with plant-based protein and spices.', '7.49', '210'),
('Paint By Numbers Kit', 'Relaxing paint kit with pre-printed canvas for painting.', '24.99', '210'),
('Marinara Sauce', 'Classic marinara sauce for all pasta dishes.', '3.49', '216'),
('Honey Almond Granola Bars', 'Chewy granola bars made with honey and almonds.', '3.99', '216'),
('Snack Container Set', 'Stackable containers for organizing snacks and treats.', '19.99', '218'),
('Kid''s Fruit Snacks', 'Assorted fruit-flavored gummy snacks that kids love.', '2.49', '218'),
('Granulated Sugar', 'Fine granulated sugar for all your baking needs.', '2.49', '219'),
('Pumpkin Seeds', 'Crunchy roasted pumpkin seeds, great for snacking.', '2.79', '22'),
('Garlic Breadsticks', 'Ready-to-bake garlic breadsticks, perfect with pasta dishes.', '3.49', '221'),
('Electric Nail File Kit', 'Professional-grade nail care set for manicures and pedicures.', '34.99', '227'),
('Eco-Friendly Yoga Blocks', 'Sustainable foam blocks for yoga practice.', '15.99', '228'),
('Hot Salsa', 'Spicy salsa made with fresh ingredients.', '2.29', '231'),
('Bamboo Cutting Board', 'Eco-friendly bamboo cutting board for food prep.', '22', '238'),
('Organic Almonds', 'Crunchy and nutritious almonds, perfect for snacking.', '8.99', '239'),
('Apricot Jam', 'Sweet and tangy jam made from natural apricots.', '4.29', '239'),
('Backpack', 'Durable and spacious backpack for travel and school.', '49.99', '239'),
('Spicy Beef Taco Mix', 'Easy mix for making spicy beef tacos.', '1.99', '239'),
('Blue Corn Tortilla Chips', 'Crunchy chips made from blue corn, perfect for dipping.', '3.49', '246'),
('Insulated Lunch Box', 'Durable lunch box designed to keep food fresh and cool.', '24.99', '25'),
('Soft Plush Throw Blanket', 'Cozy throw blanket perfect for chilly evenings.', '29.99', '250'),
('Fashionable Belt Bag', 'Trendy belt bag for hands-free carrying.', '34.99', '251'),
('Foam Building Blocks for Kids', 'Soft foam blocks perfect for building and imaginative play.', '22.99', '262'),
('First Aid Kit', 'Comprehensive first aid kit for emergency situations.', '29.99', '263'),
('Herbal Tea Infuser', 'Infuser for brewing loose-leaf herbal teas easily.', '9.99', '268'),
('Classic Cheeseburger Mix', 'All-in-one mix for easy homemade cheeseburgers, just add ground beef.', '5.49', '272'),
('Garlic Parmesan Wings', 'Frozen chicken wings with garlic parmesan sauce.', '8.99', '275'),
('Luxury Bath Robe', 'Soft and plush robe for comfort after the shower.', '49.99', '276'),
('Cauliflower Rice Stir-Fry', 'Frozen cauliflower rice blended with mixed vegetables and seasonings.', '4.99', '279'),
('Phone Screen Protector', 'Tempered glass screen protector for smartphones.', '12.99', '280'),
('Digital Drawing Tablet', 'Tablet for digital drawing and illustration work.', '79.99', '283'),
('Vegetable Korma', 'Creamy vegetable curry enriched with spices.', '6.49', '288'),
('Stainless Steel BBQ Grill Set', 'Essential tools for outdoor barbecues including tongs and spatula.', '49.99', '290'),
('Stick Vacuums Cleaner', 'Cordless vacuum cleaner for quick clean-ups.', '129.99', '292'),
('Compost Bin', 'Countertop compost bin for kitchen waste.', '29.99', '294'),
('Classic Slim Fit Shirt', 'A tailored slim fit shirt for a polished look at work.', '49.99', '294'),
('Cacao Nibs', 'Crunchy cacao nibs, great for adding to smoothies or baking.', '6.49', '295'),
('Pumpkin Spice Granola', 'Crunchy granola with pumpkin spice flavor.', '4.99', '30'),
('Air Mattress', 'Inflatable air mattress for convenient sleeping.', '49.99', '33'),
('Almond Butter Cups', 'Rich chocolate cups filled with almond butter, a delicious treat.', '3.29', '35'),
('Maple Almond Granola', 'Crunchy granola with maple flavor and almond pieces for breakfast.', '5.49', '41'),
('Graphic Print Leggings', 'Trendy leggings with a unique graphic print, versatile for workouts and casual wear.', '29.99', '42'),
('Vegetable Quinoa Bowl', 'A frozen meal featuring quinoa and mixed vegetables, ready to heat and eat.', '5.99', '54'),
('Graphic Sweatshirt', 'A comfortable sweatshirt featuring a bold graphic print.', '34.99', '55'),
('Stainless Steel Water Pitcher', 'Insulated pitcher to keep beverages cold or hot.', '39.99', '56'),
('Blue Corn Tortilla Chips', 'Crunchy chips made from blue corn, perfect for dipping.', '3.49', '58'),
('Electric Opener for Jars and Bottles', 'Easily opens jar lids and bottle caps with one touch.', '24.99', '68'),
('Dog Training Collar', 'Rechargeable training collar for effective behavior training.', '39.99', '69'),
('Beef Chili', 'Hearty beef chili, ready to heat and eat.', '4.5', '69'),
('Chocolate Raspberry Tart', 'Rich tart filled with chocolate and raspberry, a gourmet dessert.', '9.99', '70'),
('Buttermilk Pancakes', 'Fluffy pancakes with buttermilk flavor.', '3.99', '73'),
('Rechargeable Hand Warmer', 'Portable rechargeable warmer for cold days.', '22.99', '76'),
('Pet Hair Remover', 'Effective roller for removing pet hair from furniture.', '9.99', '79'),
('Tea Infuser', 'Silicone tea infuser for brewing loose leaf tea.', '12.99', '8'),
('Biodegradable Dog Waste Bags', 'Eco-friendly bags for picking up after your pet.', '14.99', '8'),
('Pet Hair Vacuum Attachment', 'Special attachment for vacuum cleaners to remove pet hair easily.', '14.99', '80'),
('Creamy Tomato Basil Soup', 'Rich and creamy tomato basil soup, perfect with a grilled cheese.', '3.29', '83'),
('High-Top Leather Boots', 'Durable high-top leather boots for the stylish adventurer.', '99.99', '84'),
('Smart Plug', 'Wi-Fi enabled plug for controlling devices from your smartphone.', '19.99', '89'),
('Pumpkin Pie Spice', 'A blend of spices that brings the taste of fall to your baked goods.', '2.99', '92');